# Generated by Django 5.0.2 on 2024-02-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='total_cattle',
            field=models.IntegerField(default=0),
        ),
    ]
