# Generated by Django 5.0.2 on 2024-02-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0002_farm_total_cattle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='total_cattle',
        ),
    ]
