# Generated by Django 5.0.2 on 2024-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_remove_farm_total_cattle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='bulls',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='cows',
        ),
        migrations.AddField(
            model_name='farm',
            name='bulls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='cows_count',
            field=models.IntegerField(default=0),
        ),
    ]
