# Generated by Django 5.0.2 on 2024-02-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0005_remove_farm_bulls_count_remove_farm_cows_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='bulls',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='cows',
        ),
        migrations.AddField(
            model_name='farm',
            name='bulls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='cows_count',
            field=models.IntegerField(default=0),
        ),
    ]
