# Generated by Django 5.0.2 on 2024-02-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0006_remove_farm_bulls_remove_farm_cows_farm_bulls_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='breed',
            field=models.CharField(choices=[('Bonsmara', 'Bonsmara'), ('Brahman', 'Brahman'), ('Jersey', 'Jersey')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='calf_count',
            field=models.IntegerField(default=0),
        ),
    ]
