# Generated by Django 5.0.2 on 2024-02-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0007_farm_breed_farm_calf_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
