# Generated by Django 5.0.2 on 2024-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0008_farm_is_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='vaccine',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin')], max_length=100, null=True),
        ),
    ]
