# Generated by Django 5.0.2 on 2024-02-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0009_farm_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='vaccine',
            field=models.BooleanField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin')], max_length=100, null=True),
        ),
    ]
