# Generated by Django 5.0.2 on 2024-02-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0011_alter_farm_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='farm',
            name='vaccine1',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='vaccine2',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='vaccine3',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin')], max_length=100, null=True),
        ),
    ]
