# Generated by Django 5.0.2 on 2024-02-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0013_remove_farm_is_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='breed',
            field=models.CharField(choices=[('Bonsmara', 'Bonsmara'), ('Brahman', 'Brahman'), ('Jersey', 'Jersey'), ('Muliple', 'Multiple')], max_length=100, null=True),
        ),
    ]
