# Generated by Django 5.0.2 on 2024-02-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0014_alter_farm_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='vaccine1',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='vaccine2',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='vaccine3',
            field=models.CharField(choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin'), ('None', 'None')], max_length=100, null=True),
        ),
    ]
