# Generated by Django 5.0.2 on 2024-02-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0015_alter_farm_vaccine1_alter_farm_vaccine2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_branded',
            field=models.BooleanField(default=False),
        ),
    ]
