# Generated by Django 5.0.2 on 2024-02-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0016_farm_is_branded'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
