# Generated by Django 5.0.2 on 2024-02-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0017_farm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='feed_cost',
            field=models.IntegerField(default=0),
        ),
    ]
