# Generated by Django 5.0.2 on 2024-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0018_farm_feed_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='pregnant_cows',
            field=models.IntegerField(default=0),
        ),
    ]
