# Generated by Django 5.0.2 on 2024-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0019_farm_pregnant_cows'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='sick',
            field=models.IntegerField(default=0),
        ),
    ]
