# Generated by Django 5.0.2 on 2024-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0020_farm_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
