# Generated by Django 5.0.2 on 2024-02-20 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0021_farm_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFeedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_app.farm')),
            ],
        ),
    ]
