# Generated by Django 5.0.2 on 2024-02-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0022_animalfeedcost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalFeedCost',
        ),
    ]
