# Generated by Django 5.0.2 on 2024-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0023_delete_animalfeedcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='feed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
