# Generated by Django 5.0.2 on 2024-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0024_alter_farm_feed_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='Feed',
            field=models.CharField(choices=[('Energie Lek', 'Energie Lek'), ('Beef Finisher', 'Beef Finisher'), ('Koei & Kalf', 'Koei & Kalf'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='feed_cost',
            field=models.FloatField(default=0),
        ),
    ]
