# Generated by Django 6.0 on 2025-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0026_farm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='Feed',
            field=models.CharField(blank=True, choices=[('Energie Lek', 'Energie Lek'), ('Beef Finisher', 'Beef Finisher'), ('Koei & Kalf', 'Koei & Kalf'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='breed',
            field=models.CharField(blank=True, choices=[('Bonsmara', 'Bonsmara'), ('Brahman', 'Brahman'), ('Jersey', 'Jersey'), ('Muliple', 'Multiple')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='vaccine1',
            field=models.CharField(blank=True, choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='vaccine2',
            field=models.CharField(blank=True, choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin'), ('None', 'None')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='vaccine3',
            field=models.CharField(blank=True, choices=[('Multivax', 'Multivax'), ('Disulfox', 'Disulfox'), ('Terramycin', 'Terramycin'), ('None', 'None')], max_length=100, null=True),
        ),
    ]
