# Generated by Django 6.0 on 2025-12-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0027_alter_farm_feed_alter_farm_breed_alter_farm_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='pregnant_cows',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='sick',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
