# Generated by Django 6.0 on 2025-12-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0028_alter_farm_pregnant_cows_alter_farm_sick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abattoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('api_url', models.CharField(blank=True, max_length=500, null=True)),
                ('species_json_paths', models.JSONField(blank=True, default=dict)),
                ('last_prices', models.JSONField(blank=True, default=dict)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
